### PR TITLE
Validate command data

### LINKED ISSUE #28: Validate command data
We should validate data passed to commands in corresponding setters (or constructors), so invalid data are not even send to Matej API (which would reject them).

Eg. user_id (and other ids) must conform (according to JSON schema) ` "type_identifier": { "type": "string", "pattern": "^[0-9A-Za-z-_]+$", "maxLength": 100 }` etc.

- Use assertion library (https://github.com/beberlei/assert or https://github.com/webmozart/assert)
- Throw custom exception
- Add information about the required value also to PHPDoc.

### PR DESCRIPTION
**Pull request by OndraM**
As mentioned in #28 , the plan is to allow setting only those values, allowed by Matej's API (and Matej JSON schema), so that you will get the feedback that your data are wrong sooner, even without sending them to Matej API (which will reject them).

I'd like to add the assertions in a similar way (via protected constructors - to not put all the assertions into constructor) to all Commands etc. Any comments, ideas?

### CODE REVIEW

File: src/Exception/DomainException.php [hunk 1]
```diff
@@ -0,0 +1,45 @@
+<?php declare(strict_types=1);
+
+namespace Lmc\Matej\Exception;
+
+use Assert\AssertionFailedException;
+
+/**
+ * Exception thrown invalid value is passed while creating domain model.
```
Comment (MarketaSebkova) [inline src/Exception/DomainException.php]: `Exception thrown when...`?

File: src/Model/Assertion.php [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+
+use Lmc\Matej\Exception\DomainException;
+
+class Assertion extends \Assert\Assertion
+{
+    protected static $exceptionClass = DomainException::class;
+
+    /**
+     * Assert value is valid Matej type identifier
+     * @param mixed $value
```
Comment (Fantomas-7) [inline src/Model/Assertion.php]: `@return`?

File: src/Model/Command/Interaction.php [hunk 3]
```diff
@@ -34,12 +36,12 @@ private function __construct(
...
-        $this->itemId = $itemId; // TODO: assert format
-        $this->value = $value; // TODO: assert value between 0-1
-        $this->context = $context; // TODO: assert format
-        $this->timestamp = $timestamp ?: time(); // TODO: assert format
+        $this->setInteractionType($interactionType);
+        $this->setUserId($userId);
+        $this->setItemId($itemId);
+        $this->setValue($value);
+        $this->setContext($context);
+        $this->setTimestamp($timestamp ?: time());
```
Comment (ghost) [inline src/Model/Command/Interaction.php]: Why not use `??` instead of `?:`

File: src/Model/Command/Interaction.php [hunk 4]
```diff
@@ -121,4 +123,51 @@ public function getCommandParameters(): array
...
+    protected function setContext(string $context): void
+    {
+        Assertion::typeIdentifier($context);
+
+        $this->context = $context;
+    }
+
+    protected function setTimestamp(int $timestamp): void
+    {
+        Assertion::greaterThan($timestamp, 0);
```
Comment (ghost) [inline src/Model/Command/Interaction.php:157]: Isn't `$timestamp = 0` technically valid?

**Review by ghost — CHANGES_REQUESTED** [review]

**Review by MarketaSebkova — CHANGES_REQUESTED** [review]

File: src/Model/Command/Interaction.php (hunk 3 above)
Comment (OndraM) [reply src/Model/Command/Interaction.php]: `??` is useful when the value may not be set. But the `$timestamp` is always set (but may be null).

File: src/Model/Command/Interaction.php (hunk 4 above)
Comment (OndraM) [reply src/Model/Command/Interaction.php:157]: Technically maybe yes, but not as per Matej JSON schema: `"type_timestamp": { "type": "integer", "minimum": 1 },`

File: src/Model/Command/Interaction.php (hunk 3 above)
Comment (ghost) [reply src/Model/Command/Interaction.php]: `??` is also useful when the value might be `null`, which is the default value here. With `?:` both `null` and `0` get coalesced to `time()`. I just wasn't sure if that was intended.

File: src/Model/Command/Interaction.php (hunk 4 above)
Comment (ghost) [reply src/Model/Command/Interaction.php:157]: ¯\\\_(ツ)\_/¯

File: src/Model/Command/Interaction.php (hunk 3 above)
Comment (OndraM) [reply src/Model/Command/Interaction.php]: I will change the condition to `$timestamp === null`  to clearly state this covers the case when no value is passed (ie. default value should be used).

File: src/Model/Command/ItemPropertySetup.php [hunk 5]
```diff
@@ -58,6 +57,27 @@ public static function set(string $propertyName): self
...
+    protected function setPropertyName(string $propertyName): void
+    {
+        Assertion::typeIdentifier($propertyName);
+
+        $this->propertyName = $propertyName;
+    }
+
+    protected function setPropertyType(string $propertyType): void
+    {
+        Assertion::choice($propertyType, [
```
Comment (jirinovak) [inline src/Model/Command/ItemPropertySetup.php]: This is redundant, isn't it?

I cannot create invalid `ItemPropertySetup` cause private `constructor`.

And factory constructors are covered by tests.

**Review by davidkmenta — DISMISSED** [review]

**Review by jirinovak — DISMISSED** [review]
